"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class StatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TOTAL_WAGONS_FIELD_NUMBER: builtins.int
    TOTAL_PASSENGERS_FIELD_NUMBER: builtins.int
    WAITING_PASSENGERS_FIELD_NUMBER: builtins.int
    total_wagons: builtins.int
    total_passengers: builtins.int
    waiting_passengers: builtins.int
    def __init__(
        self,
        *,
        total_wagons: builtins.int = ...,
        total_passengers: builtins.int = ...,
        waiting_passengers: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["total_passengers", b"total_passengers", "total_wagons", b"total_wagons", "waiting_passengers", b"waiting_passengers"]) -> None: ...

global___StatusResponse = StatusResponse

@typing.final
class RegistrationRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HOST_FIELD_NUMBER: builtins.int
    PORT_FIELD_NUMBER: builtins.int
    host: builtins.str
    port: builtins.int
    def __init__(
        self,
        *,
        host: builtins.str = ...,
        port: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["host", b"host", "port", b"port"]) -> None: ...

global___RegistrationRequest = RegistrationRequest

@typing.final
class RegistrationResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    ID_FIELD_NUMBER: builtins.int
    SUCCESS_FIELD_NUMBER: builtins.int
    id: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        id: builtins.int = ...,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["id", b"id", "success", b"success"]) -> None: ...

global___RegistrationResponse = RegistrationResponse

@typing.final
class passenger_list(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PASSENGER_ID_FIELD_NUMBER: builtins.int
    @property
    def passenger_id(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(
        self,
        *,
        passenger_id: collections.abc.Iterable[builtins.int] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["passenger_id", b"passenger_id"]) -> None: ...

global___passenger_list = passenger_list
