# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from proto import rollercoaster_pb2 as proto_dot_rollercoaster__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/rollercoaster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class wagonStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.depart = channel.unary_unary(
                '/rollercoaster.wagon/depart',
                request_serializer=proto_dot_rollercoaster__pb2.passenger_list.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class wagonServicer(object):
    """Missing associated documentation comment in .proto file."""

    def depart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_wagonServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'depart': grpc.unary_unary_rpc_method_handler(
                    servicer.depart,
                    request_deserializer=proto_dot_rollercoaster__pb2.passenger_list.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rollercoaster.wagon', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rollercoaster.wagon', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class wagon(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def depart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.wagon/depart',
            proto_dot_rollercoaster__pb2.passenger_list.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class passengerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.i_am_disembarking = channel.unary_unary(
                '/rollercoaster.passenger/i_am_disembarking',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.i_am_boarding = channel.unary_unary(
                '/rollercoaster.passenger/i_am_boarding',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class passengerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def i_am_disembarking(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def i_am_boarding(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_passengerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'i_am_disembarking': grpc.unary_unary_rpc_method_handler(
                    servicer.i_am_disembarking,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'i_am_boarding': grpc.unary_unary_rpc_method_handler(
                    servicer.i_am_boarding,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rollercoaster.passenger', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rollercoaster.passenger', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class passenger(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def i_am_disembarking(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.passenger/i_am_disembarking',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def i_am_boarding(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.passenger/i_am_boarding',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class rollercoasterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.get_status = channel.unary_unary(
                '/rollercoaster.rollercoaster/get_status',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_rollercoaster__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.register_wagon = channel.unary_unary(
                '/rollercoaster.rollercoaster/register_wagon',
                request_serializer=proto_dot_rollercoaster__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_rollercoaster__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.register_passenger = channel.unary_unary(
                '/rollercoaster.rollercoaster/register_passenger',
                request_serializer=proto_dot_rollercoaster__pb2.RegistrationRequest.SerializeToString,
                response_deserializer=proto_dot_rollercoaster__pb2.RegistrationResponse.FromString,
                _registered_method=True)
        self.arrive = channel.unary_unary(
                '/rollercoaster.rollercoaster/arrive',
                request_serializer=proto_dot_rollercoaster__pb2.arrive_request.SerializeToString,
                response_deserializer=proto_dot_rollercoaster__pb2.arrive_response.FromString,
                _registered_method=True)


class rollercoasterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def get_status(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register_wagon(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def register_passenger(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def arrive(self, request, context):
        """finished ride -> start disembarking
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_rollercoasterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'get_status': grpc.unary_unary_rpc_method_handler(
                    servicer.get_status,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=proto_dot_rollercoaster__pb2.StatusResponse.SerializeToString,
            ),
            'register_wagon': grpc.unary_unary_rpc_method_handler(
                    servicer.register_wagon,
                    request_deserializer=proto_dot_rollercoaster__pb2.RegistrationRequest.FromString,
                    response_serializer=proto_dot_rollercoaster__pb2.RegistrationResponse.SerializeToString,
            ),
            'register_passenger': grpc.unary_unary_rpc_method_handler(
                    servicer.register_passenger,
                    request_deserializer=proto_dot_rollercoaster__pb2.RegistrationRequest.FromString,
                    response_serializer=proto_dot_rollercoaster__pb2.RegistrationResponse.SerializeToString,
            ),
            'arrive': grpc.unary_unary_rpc_method_handler(
                    servicer.arrive,
                    request_deserializer=proto_dot_rollercoaster__pb2.arrive_request.FromString,
                    response_serializer=proto_dot_rollercoaster__pb2.arrive_response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'rollercoaster.rollercoaster', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('rollercoaster.rollercoaster', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class rollercoaster(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def get_status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.rollercoaster/get_status',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            proto_dot_rollercoaster__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def register_wagon(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.rollercoaster/register_wagon',
            proto_dot_rollercoaster__pb2.RegistrationRequest.SerializeToString,
            proto_dot_rollercoaster__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def register_passenger(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.rollercoaster/register_passenger',
            proto_dot_rollercoaster__pb2.RegistrationRequest.SerializeToString,
            proto_dot_rollercoaster__pb2.RegistrationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def arrive(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/rollercoaster.rollercoaster/arrive',
            proto_dot_rollercoaster__pb2.arrive_request.SerializeToString,
            proto_dot_rollercoaster__pb2.arrive_response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
